//! Server protocol e2e tests

#[cfg(feature = "bgp")]
pub mod bgp;
#[cfg(feature = "rip")]
pub mod rip;
#[cfg(feature = "cassandra")]
pub mod cassandra;
// DataLink doesn't have a feature flag, it's always available
pub mod datalink;
#[cfg(feature = "dhcp")]
pub mod dhcp;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "dot")]
pub mod dot;
#[cfg(feature = "doh")]
pub mod doh;
#[cfg(feature = "dynamo")]
pub mod dynamo;
#[cfg(feature = "elasticsearch")]
pub mod elasticsearch;
#[cfg(feature = "git")]
pub mod git;
#[cfg(feature = "grpc")]
pub mod grpc;
#[cfg(feature = "etcd")]
pub mod etcd;
#[cfg(feature = "http")]
pub mod http;
#[cfg(feature = "imap")]
pub mod imap;
#[cfg(feature = "ipp")]
pub mod ipp;
#[cfg(feature = "ipsec")]
pub mod ipsec;
#[cfg(feature = "irc")]
pub mod irc;
#[cfg(feature = "xmpp")]
pub mod xmpp;
#[cfg(feature = "ldap")]
pub mod ldap;
#[cfg(feature = "mcp")]
pub mod mcp;
#[cfg(feature = "mdns")]
pub mod mdns;
#[cfg(feature = "mqtt")]
pub mod mqtt;
#[cfg(feature = "mysql")]
pub mod mysql;
#[cfg(feature = "nfs")]
pub mod nfs;
#[cfg(feature = "ntp")]
pub mod ntp;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "openapi")]
pub mod openapi;
#[cfg(feature = "jsonrpc")]
pub mod jsonrpc;
#[cfg(feature = "kafka")]
pub mod kafka;
#[cfg(feature = "openvpn")]
pub mod openvpn;
#[cfg(feature = "postgresql")]
pub mod postgresql;
#[cfg(feature = "proxy")]
pub mod proxy;
#[cfg(feature = "redis")]
pub mod redis;
#[cfg(feature = "smb")]
pub mod smb;
#[cfg(feature = "smtp")]
pub mod smtp;
#[cfg(feature = "snmp")]
pub mod snmp;
#[cfg(feature = "socks5")]
pub mod socks5;
#[cfg(feature = "s3")]
pub mod s3;
#[cfg(feature = "sqs")]
pub mod sqs;
#[cfg(feature = "ssh")]
pub mod ssh;
#[cfg(feature = "stun")]
pub mod stun;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(feature = "telnet")]
pub mod telnet;
#[cfg(feature = "tor")]
pub mod tor_directory;
#[cfg(feature = "tor")]
pub mod tor_relay;
#[cfg(feature = "tor")]
pub mod tor_integration;
#[cfg(feature = "turn")]
pub mod turn;
#[cfg(feature = "udp")]
pub mod udp;
#[cfg(feature = "vnc")]
pub mod vnc;
#[cfg(feature = "webdav")]
pub mod webdav;
#[cfg(feature = "wireguard")]
pub mod wireguard;
#[cfg(feature = "xmlrpc")]
pub mod xmlrpc;

// Shared test helpers
pub mod helpers;
