//! TUI event loop - full-screen terminal user interface
//!
//! This module implements the interactive TUI mode with keyboard input,
//! network events, and LLM-driven command interpretation.

use anyhow::Result;
use crossterm::event::{Event, EventStream, KeyCode, KeyModifiers};
use futures::StreamExt;
use ratatui::{backend::CrosstermBackend, Terminal};
use std::io;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::{mpsc, Mutex};
use tokio::time::interval;
use tracing::{error, info};

use crate::events::{AppEvent, EventHandler, UserCommand};
use crate::llm::OllamaClient;
use crate::settings::Settings;
use crate::state::app_state::AppState;
use crate::ui::{events as ui_events, layout, App};

/// Run the interactive TUI mode
pub async fn run_tui(
    state: AppState,
    mut app: App,
    mut event_handler: EventHandler,
    _llm_client: OllamaClient,
    settings: Settings,
    args: &super::Args,
) -> Result<()> {
    info!("Starting TUI mode");

    // Override model if specified in args, otherwise use settings
    let effective_model = if let Some(model) = &args.model {
        model.clone()
    } else {
        settings.model.clone()
    };

    state.set_ollama_model(effective_model.clone()).await;
    app.connection_info.model = effective_model;

    // Add welcome messages
    app.add_message("NetGet - LLM-Controlled Network Application".to_string());
    app.add_message("All protocol responses are generated by LLM".to_string());
    app.add_message("".to_string());
    app.add_message("Supported protocol stacks:".to_string());
    app.add_message("  TCP (Beta): \"Pretend to be FTP server on port 2121; serve file accounts.csv with 'balance,0'\"".to_string());
    app.add_message("  HTTP (Beta): \"Pretend to be a sassy HTTP server on port 8080 serving cooking recipes\"".to_string());
    app.add_message("  SSH/SFTP (Beta): \"Pretent to be a shell via SSH on port 2222\"".to_string());
    app.add_message("  NTP (Beta; root-only): \"pretend to be a ntp server on port 123\"".to_string());
    app.add_message("  SNMP (Alpha): \"SNMP Port 8161 serve OID 1.3.6.1.2.1.1.1.0 (sysDescr) return 'NetGet SNMP Server v0.1'\"".to_string());
    app.add_message("  Ethernet (Stub; root-only)".to_string());
    app.add_message("  UDP (Stub)".to_string());
    app.add_message("  DHCP (Stub)".to_string());
    app.add_message("  IRC (Stub)".to_string());
    app.add_message("  DNS (Stub)".to_string());
    app.add_message("".to_string());
    app.add_message("Other prompts:".to_string());
    app.add_message("  ".to_string());
    app.add_message("".to_string());

    // Setup terminal
    let mut terminal = Terminal::new(CrosstermBackend::new(io::stdout()))?;
    terminal.clear()?;

    // Create status channel for server messages
    let (status_tx, mut status_rx) = mpsc::unbounded_channel::<String>();

    // Wrap settings for sharing
    let _settings = Arc::new(Mutex::new(settings));

    // Create keyboard event stream
    let mut event_stream = EventStream::new();

    // Create tick interval for UI updates
    let mut tick_interval = interval(Duration::from_millis(100));

    // Cleanup configuration constants
    const CLEANUP_INTERVAL_SECS: u64 = 5;
    const SERVER_CLEANUP_TIMEOUT_SECS: u64 = 30;
    const CONNECTION_CLEANUP_TIMEOUT_SECS: u64 = 10;
    const CONNECTIONLESS_CLEANUP_TIMEOUT_SECS: u64 = 10;

    // Create cleanup interval (runs every 5 seconds to clean up old servers/connections)
    let mut cleanup_interval = interval(Duration::from_secs(CLEANUP_INTERVAL_SECS));

    // Main event loop
    info!("Entering main event loop");
    loop {
        // Draw UI
        if let Err(e) = terminal.draw(|f| layout::render(f, &mut app)) {
            error!("Terminal draw error: {}", e);
            return Err(e.into());
        }

        // Drain status messages from spawned tasks
        let mut ui_needs_update = false;
        while let Ok(msg) = status_rx.try_recv() {
            if msg == "__UPDATE_UI__" {
                // Special signal to update UI from state (drain all duplicates)
                ui_needs_update = true;
            } else if msg.starts_with("__STATS_SENT__") {
                // Special signal to update sent bytes stats
                if let Ok(bytes) = msg.strip_prefix("__STATS_SENT__").unwrap().parse::<u64>() {
                    app.packet_stats.bytes_sent += bytes;
                }
            } else {
                // Filter messages by log level
                use crate::ui::app::LogLevel;
                let should_show = if msg.starts_with("[ERROR]") {
                    // ERROR always shown
                    true
                } else if msg.starts_with("[WARN]") {
                    app.log_level >= LogLevel::Warn
                } else if msg.starts_with("[INFO]") {
                    app.log_level >= LogLevel::Info
                } else if msg.starts_with("[DEBUG]") {
                    app.log_level >= LogLevel::Debug
                } else if msg.starts_with("[TRACE]") {
                    app.log_level >= LogLevel::Trace
                } else {
                    // Unprefixed messages always show
                    true
                };

                if should_show {
                    app.add_status_message(msg);
                }
            }
        }

        // Update UI once after draining all messages
        if ui_needs_update {
            update_ui_from_state(&mut app, &state).await;
        }

        tracing::debug!("Starting select");
        tokio::select! {
            // Keyboard events
            maybe_event = event_stream.next() => {
                tracing::debug!("Got event from stream");
                match maybe_event {
                    Some(Ok(event)) => {
                        if handle_keyboard_event(event, &mut app, &state, &mut event_handler, &status_tx).await? {
                            info!("Quit requested by user");
                            break; // Quit requested
                        }
                    }
                    Some(Err(e)) => {
                        error!("Keyboard event error: {}", e);
                    }
                    None => {
                        // Event stream ended
                        info!("Event stream ended unexpectedly");
                        break;
                    }
                }
            }

            // Periodic tick for UI updates
            _ = tick_interval.tick() => {
                // Just triggers redraw
            }

            // Periodic cleanup of old servers and connections
            _ = cleanup_interval.tick() => {
                // Clean up stopped/error servers
                state.cleanup_old_servers(SERVER_CLEANUP_TIMEOUT_SECS).await;
                // Clean up closed connections
                state.cleanup_closed_connections(CONNECTION_CLEANUP_TIMEOUT_SECS).await;
                // Clean up old connectionless protocol entries
                state.cleanup_old_connections(CONNECTIONLESS_CLEANUP_TIMEOUT_SECS).await;
            }
        }
    }

    // Save command history before exiting
    let _ = app.save_history();
    info!("TUI mode exited");

    Ok(())
}

/// Handle keyboard events
/// Returns true if quit was requested
async fn handle_keyboard_event(
    event: Event,
    app: &mut App,
    state: &AppState,
    event_handler: &mut EventHandler,
    _status_tx: &mpsc::UnboundedSender<String>,
) -> Result<bool> {
    match event {
        Event::Key(key) => {
            // Special handling for Tab and Enter with LLM
            match key.code {
                KeyCode::Tab => {
                    app.toggle_focus();
                    return Ok(false);
                }

                // Any modifier + N inserts a newline (Ctrl+N, Alt+N, Cmd+N, etc.) - except Shift alone
                // More mnemonic than Ctrl+O and works reliably across all terminals
                KeyCode::Char('n') | KeyCode::Char('N') if app.is_input_focused() && {
                    let mods = key.modifiers;
                    !mods.is_empty() && mods != KeyModifiers::SHIFT
                } => {
                    app.insert_newline();
                    return Ok(false);
                }

                // Shift+Enter, Alt+Enter, or Ctrl+Enter inserts a newline (for terminals that support it)
                // Note: Many terminals don't report modifiers with Enter key
                KeyCode::Enter if app.is_input_focused() && (
                    key.modifiers.contains(KeyModifiers::SHIFT) ||
                    key.modifiers.contains(KeyModifiers::ALT) ||
                    key.modifiers.contains(KeyModifiers::CONTROL)
                ) => {
                    app.insert_newline();
                    return Ok(false);
                }

                // Plain Enter submits the form
                KeyCode::Enter if app.is_input_focused() => {
                    let input = app.submit_input();
                    if !input.is_empty() {
                        app.add_status_message(format!("[USER] {}", input));

                        // Parse command
                        let command = UserCommand::parse(&input);

                        // Check if it's a slash command (handle immediately) or needs LLM
                        match command {
                            UserCommand::Status | UserCommand::ShowModel | UserCommand::ChangeModel {..} | UserCommand::ShowLogLevel | UserCommand::ChangeLogLevel {..} | UserCommand::Quit | UserCommand::UnknownSlashCommand {..} => {
                                // Handle slash commands synchronously (they're fast)
                                match event_handler
                                    .handle_event(AppEvent::UserCommand(command), app)
                                    .await
                                {
                                    Ok(should_quit) => {
                                        if should_quit {
                                            return Ok(true); // Exit the TUI
                                        }
                                    }
                                    Err(e) => {
                                        app.add_llm_message(format!("Error: {}", e));
                                    }
                                }
                                update_ui_from_state(app, state).await;
                            }
                            UserCommand::Interpret { input: llm_input } => {
                                // Spawn async task to process with LLM (prevents UI freeze)
                                let mut handler_clone = event_handler.clone();
                                let status_tx_clone = _status_tx.clone();
                                tokio::spawn(async move {
                                    let _ = handler_clone.handle_interpret(llm_input, status_tx_clone).await;
                                });
                                // UI will be updated when messages arrive via status_tx
                            }
                        }
                    }
                    return Ok(false);
                }

                _ => {}
            }

            // Use existing keyboard handler from ui module
            if ui_events::handle_key_event(app, key)? {
                return Ok(true); // Quit requested (e.g., Ctrl-C)
            }
        }
        _ => {}
    }

    Ok(false)
}

/// Update UI with current application state
async fn update_ui_from_state(app: &mut App, state: &AppState) {
    use crate::ui::app::{ServerDisplayInfo, ConnectionDisplayInfo};

    app.connection_info.mode = format!("{}", state.get_mode().await);
    app.connection_info.model = state.get_ollama_model().await;

    // Update server list
    let servers = state.get_all_servers().await;
    app.servers = servers.iter().map(|s| ServerDisplayInfo {
        id: format!("#{}", s.id.as_u32()),
        protocol: s.base_stack.to_string(),
        port: s.port,
        status: s.status.to_string(),
        connections: s.connections.len(),
    }).collect();

    // Update connection list (aggregate from all servers)
    // Use global connection IDs from the app's counter
    app.connections = servers.iter().flat_map(|s| {
        s.connections.values().map(|conn| {
            let network_conn_id = conn.id.to_string();
            let global_id = app.get_or_allocate_connection_id(network_conn_id);
            ConnectionDisplayInfo {
                id: global_id,
                server_id: format!("#{}", s.id.as_u32()),
                address: conn.remote_addr.to_string(),
                state: match conn.status {
                    crate::state::server::ConnectionStatus::Active => "Active".to_string(),
                    crate::state::server::ConnectionStatus::Closed => "Closed".to_string(),
                },
            }
        }).collect::<Vec<_>>()
    }).collect();

    // Update legacy fields for backwards compatibility
    if let Some(first_server) = servers.first() {
        app.connection_info.protocol = first_server.base_stack.to_string();
        if let Some(addr) = first_server.local_addr {
            app.connection_info.local_addr = Some(addr.to_string());
        }
    }
}

