//! Client protocol e2e tests

#[cfg(feature = "amqp")]
pub mod amqp;
#[cfg(feature = "arp")]
pub mod arp;
#[cfg(feature = "bitcoin")]
pub mod bitcoin;
#[cfg(feature = "bootp")]
pub mod bootp;
#[cfg(feature = "couchdb")]
pub mod couchdb;
#[cfg(feature = "datalink")]
pub mod datalink;
#[cfg(feature = "dc")]
pub mod dc;
#[cfg(feature = "dhcp")]
pub mod dhcp;
#[cfg(feature = "dns")]
pub mod dns;
#[cfg(feature = "ftp")]
pub mod ftp;
#[cfg(feature = "grpc")]
pub mod grpc;
#[cfg(feature = "http")]
pub mod http;
#[cfg(feature = "http2")]
pub mod http2;
#[cfg(feature = "http3")]
pub mod http3;
#[cfg(feature = "icmp")]
pub mod icmp;
#[cfg(feature = "ipp")]
pub mod ipp;
#[cfg(feature = "irc")]
pub mod irc;
#[cfg(feature = "jsonrpc")]
pub mod jsonrpc;
#[cfg(feature = "kafka")]
pub mod kafka;
#[cfg(feature = "mcp")]
pub mod mcp;
#[cfg(feature = "mdns")]
pub mod mdns;
#[cfg(feature = "mongodb")]
pub mod mongodb;
#[cfg(feature = "mssql")]
pub mod mssql;
#[cfg(feature = "mysql")]
pub mod mysql;
#[cfg(feature = "nfs")]
pub mod nfs;
#[cfg(feature = "ntp")]
pub mod ntp;
#[cfg(feature = "ollama")]
pub mod ollama;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "openapi")]
pub mod openapi;
#[cfg(feature = "ospf")]
pub mod ospf;
#[cfg(feature = "postgresql")]
pub mod postgresql;
#[cfg(feature = "pypi")]
pub mod pypi;
#[cfg(feature = "redis")]
pub mod redis;
#[cfg(feature = "rip")]
pub mod rip;
#[cfg(feature = "s3")]
pub mod s3;
#[cfg(feature = "saml")]
pub mod saml;
#[cfg(feature = "snmp")]
pub mod snmp;
#[cfg(feature = "socket_file")]
pub mod socket_file;
#[cfg(feature = "socks5")]
pub mod socks5;
#[cfg(feature = "sqs")]
pub mod sqs;
#[cfg(feature = "ssh")]
pub mod ssh;
#[cfg(all(feature = "ssh-agent", unix))]
pub mod ssh_agent;
#[cfg(feature = "stun")]
pub mod stun;
#[cfg(feature = "syslog")]
pub mod syslog;
#[cfg(feature = "tcp")]
pub mod tcp;
#[cfg(feature = "telnet")]
pub mod telnet;
#[cfg(feature = "tls")]
pub mod tls;
#[cfg(feature = "tor")]
pub mod tor;
#[cfg(feature = "udp")]
pub mod udp;
#[cfg(feature = "webdav")]
pub mod webdav;
#[cfg(feature = "webrtc")]
pub mod webrtc;
#[cfg(feature = "whois")]
pub mod whois;
#[cfg(feature = "wireguard")]
pub mod wireguard;
