//! Prompt snapshot tests
//!
//! These tests verify that prompts generated by Easy mode and other protocols
//! are correct and remain stable.

#[cfg(all(test, feature = "http"))]
mod http_easy_test;
