//! NetGet - LLM-Controlled Network Application
//!
//! Main entry point and event loop

use anyhow::Result;
use crossterm::{
    event::KeyCode,
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ratatui::{backend::CrosstermBackend, Terminal};
use std::io;
use std::time::Duration;
use tokio::sync::mpsc;
use tracing::{debug, info, error};
use tracing_subscriber::{fmt, prelude::*, EnvFilter};

use netget::events::{AppEvent, EventHandler, NetworkEvent, UserCommand};
use netget::llm::{OllamaClient, PromptBuilder};
use netget::network::{ConnectionId, TcpServer};
use netget::state::app_state::AppState;
use netget::ui::{App, UiEvent};

#[tokio::main]
async fn main() -> Result<()> {
    // Initialize logging
    tracing_subscriber::registry()
        .with(fmt::layer().with_writer(io::stderr))
        .with(EnvFilter::from_default_env().add_directive(tracing::Level::INFO.into()))
        .init();

    info!("NetGet starting...");

    // Run the application
    let result = run_app().await;

    // Clean up
    if let Err(e) = result {
        error!("Application error: {}", e);
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }

    Ok(())
}

async fn run_app() -> Result<()> {
    // Initialize terminal
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    // Create application state
    let state = AppState::new();

    // Create Ollama clients (one for event handler, one for main loop)
    let llm_for_handler = OllamaClient::default();
    let llm = OllamaClient::default();

    // Create UI app
    let mut app = App::new();
    app.add_llm_message("NetGet - LLM-Controlled Network Application".to_string());
    app.add_llm_message("All protocol responses are generated by LLM".to_string());
    app.add_llm_message("".to_string());
    app.add_llm_message("Example commands:".to_string());
    app.add_llm_message("  - listen on port 21 via ftp".to_string());
    app.add_llm_message("  - listen on port 80 via http".to_string());
    app.add_llm_message("  - listen on port 1234".to_string());
    app.add_llm_message("  - Also serve file data.txt with content 'hello'".to_string());
    app.add_llm_message("  - model deepseek-coder:latest (change LLM model)".to_string());
    app.add_llm_message("  - model llama3.2:latest".to_string());
    app.add_llm_message("".to_string());
    app.add_llm_message("Press Ctrl+C to quit.".to_string());

    // Set initial model display
    app.connection_info.model = state.get_ollama_model().await;

    // Create event channels
    let (network_tx, mut network_rx) = mpsc::unbounded_channel::<NetworkEvent>();

    // Shared connection storage (write halves only, read halves are in separate tasks)
    use std::collections::HashMap;
    use std::sync::Arc;
    use tokio::sync::Mutex;
    type WriteHalfMap = Arc<Mutex<HashMap<ConnectionId, Arc<Mutex<tokio::io::WriteHalf<tokio::net::TcpStream>>>>>>;
    let connections: WriteHalfMap = Arc::new(Mutex::new(HashMap::new()));

    // Create event handler
    let mut event_handler = EventHandler::new(state.clone(), llm_for_handler);

    // Main event loop
    let result = 'main_loop: loop {
        // Render UI
        terminal.draw(|f| {
            let area = f.area();
            app.render(f, area);
        })?;

        // Poll for UI events (with timeout)
        if let Some(ui_event) = netget::ui::events::poll_event(Duration::from_millis(100))? {
            match ui_event {
                UiEvent::Key(key) => {
                    if key.code == KeyCode::Enter {
                        // Submit user input
                        let input = app.submit_input();
                        if !input.is_empty() {
                            app.add_status_message(format!("> {}", input));

                            // Parse user command
                            let command = UserCommand::parse(&input);

                            // Special handling for listen command
                            match command.clone() {
                                UserCommand::Listen { port, protocol: _ } => {
                                    // Handle listen command
                                    if let Err(e) = event_handler.handle_event(
                                        AppEvent::UserCommand(command),
                                        &mut app
                                    ).await {
                                        app.add_llm_message(format!("Error: {}", e));
                                        continue;
                                    }

                                    // Create a new TCP server for this listen command
                                    let mut tcp_server = TcpServer::new(network_tx.clone());

                                    // Start listening
                                    let addr: std::net::SocketAddr = format!("0.0.0.0:{}", port).parse()?;
                                    if let Err(e) = tcp_server.listen(addr).await {
                                        app.add_llm_message(format!("Failed to listen: {}", e));
                                        continue;
                                    }

                                    let local_addr = tcp_server.local_addr()
                                        .map(|a| a.to_string())
                                        .unwrap_or_default();

                                    app.connection_info.local_addr = Some(local_addr);
                                    app.connection_info.state = "Listening".to_string();

                                    // Spawn task to accept connections
                                    let network_tx_clone = network_tx.clone();
                                    let connections_clone = connections.clone();

                                    tokio::spawn(async move {
                                        loop {
                                            match tcp_server.accept().await {
                                                Ok(Some((stream, remote_addr))) => {
                                                    let connection_id = ConnectionId::new();
                                                    info!("Accepted connection {} from {}", connection_id, remote_addr);

                                                    // Split stream into read and write halves to avoid deadlock
                                                    let (read_half, write_half) = tokio::io::split(stream);

                                                    // Store write half in shared HashMap
                                                    let write_half_arc = Arc::new(Mutex::new(write_half));
                                                    connections_clone.lock().await.insert(connection_id, write_half_arc);

                                                    // Send connected event
                                                    let _ = network_tx_clone.send(NetworkEvent::Connected {
                                                        connection_id,
                                                        remote_addr,
                                                    });

                                                    // Spawn read task for this connection
                                                    let network_tx_inner = network_tx_clone.clone();
                                                    tokio::spawn(async move {
                                                        use tokio::io::AsyncReadExt;
                                                        let mut buffer = vec![0u8; 8192];
                                                        let mut read_half = read_half;

                                                        loop {
                                                            match read_half.read(&mut buffer).await {
                                                                Ok(0) => {
                                                                    info!("Connection {} closed", connection_id);
                                                                    let _ = network_tx_inner.send(NetworkEvent::Disconnected { connection_id });
                                                                    break;
                                                                }
                                                                Ok(n) => {
                                                                    use bytes::Bytes;
                                                                    let data = Bytes::copy_from_slice(&buffer[..n]);
                                                                    debug!("Received {} bytes from {}", n, connection_id);
                                                                    let _ = network_tx_inner.send(NetworkEvent::DataReceived {
                                                                        connection_id,
                                                                        data,
                                                                    });
                                                                }
                                                                Err(e) => {
                                                                    error!("Read error on {}: {}", connection_id, e);
                                                                    let _ = network_tx_inner.send(NetworkEvent::Error {
                                                                        connection_id: Some(connection_id),
                                                                        error: e.to_string(),
                                                                    });
                                                                    break;
                                                                }
                                                            }
                                                        }
                                                    });
                                                }
                                                Ok(None) => break,
                                                Err(e) => {
                                                    error!("Accept error: {}", e);
                                                    break;
                                                }
                                            }
                                        }
                                    });
                                }
                                _ => {
                                    // Handle other commands
                                    if event_handler.handle_event(
                                        AppEvent::UserCommand(command),
                                        &mut app
                                    ).await? {
                                        break 'main_loop Ok(());
                                    }
                                }
                            }
                        }
                    } else if netget::ui::events::handle_key_event(&mut app, key)? {
                        // Quit signal
                        break 'main_loop Ok(());
                    }
                }
                UiEvent::Resize(_, _) => {
                    // Terminal resized, will re-render on next iteration
                }
                UiEvent::Tick => {
                    // Periodic update
                }
            }
        }

        // Check for network events and handle them with LLM
        while let Ok(net_event) = network_rx.try_recv() {
            match &net_event {
                NetworkEvent::Connected { connection_id, remote_addr } => {
                    app.add_status_message(format!("Connection {} from {}", connection_id, remote_addr));

                    // Call LLM for initial greeting
                    let model = state.get_ollama_model().await;
                    let prompt = PromptBuilder::build_connection_established_prompt(&state, *connection_id).await;

                    match llm.generate(&model, &prompt).await {
                        Ok(response) => {
                            let response = response.trim();
                            if !response.is_empty() && response != "NO_RESPONSE" {
                                // Send response using shared connections
                                if let Some(write_half_arc) = connections.lock().await.get(connection_id) {
                                    use tokio::io::AsyncWriteExt;
                                    let mut write_half = write_half_arc.lock().await;
                                    if let Err(e) = write_half.write_all(response.as_bytes()).await {
                                        error!("Write error: {}", e);
                                    } else if let Err(e) = write_half.flush().await {
                                        error!("Flush error: {}", e);
                                    } else {
                                        app.add_status_message(format!("Sent {} bytes to {}", response.len(), connection_id));
                                    }
                                }
                            }
                        }
                        Err(e) => {
                            error!("LLM error: {}", e);
                            app.add_llm_message(format!("LLM error: {}", e));
                        }
                    }
                }
                NetworkEvent::DataReceived { connection_id, data } => {
                    app.add_status_message(format!("Received {} bytes from {}", data.len(), connection_id));

                    // Call LLM for response
                    let model = state.get_ollama_model().await;
                    let prompt = PromptBuilder::build_data_received_prompt(&state, *connection_id, data).await;

                    app.add_status_message("Asking LLM for response...".to_string());

                    match llm.generate(&model, &prompt).await {
                        Ok(response) => {
                            let response = response.trim();
                            if response == "CLOSE_CONNECTION" {
                                if let Some(write_half_arc) = connections.lock().await.remove(connection_id) {
                                    drop(write_half_arc); // Close the connection
                                    app.add_status_message(format!("Closed connection {}", connection_id));
                                }
                            } else if !response.is_empty() && response != "NO_RESPONSE" {
                                // Send response
                                if let Some(write_half_arc) = connections.lock().await.get(connection_id) {
                                    use tokio::io::AsyncWriteExt;
                                    let mut write_half = write_half_arc.lock().await;
                                    if let Err(e) = write_half.write_all(response.as_bytes()).await {
                                        error!("Write error: {}", e);
                                    } else if let Err(e) = write_half.flush().await {
                                        error!("Flush error: {}", e);
                                    } else {
                                        app.add_status_message(format!("Sent {} bytes to {}", response.len(), connection_id));
                                    }
                                }
                            } else {
                                app.add_status_message("LLM: No response needed".to_string());
                            }
                        }
                        Err(e) => {
                            error!("LLM error: {}", e);
                            app.add_llm_message(format!("LLM error: {}", e));
                        }
                    }
                }
                _ => {
                    // Handle other events with EventHandler
                    if event_handler.handle_event(AppEvent::Network(net_event), &mut app).await? {
                        break 'main_loop Ok(());
                    }
                }
            }
        }

        // Update UI stats from state
        if let Some(conns) = state.get_all_connections().await.first() {
            app.packet_stats.packets_received = conns.packets_received;
            app.packet_stats.packets_sent = conns.packets_sent;
            app.packet_stats.bytes_received = conns.bytes_received;
            app.packet_stats.bytes_sent = conns.bytes_sent;
        }

        // Update model display
        app.connection_info.model = state.get_ollama_model().await;
    };

    // Restore terminal
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    terminal.show_cursor()?;

    result
}
